##
## tinflib  -  tiny inflate library (inflate, gzip, zlib)
##
## MinGW / Cygwin makefile
##
## Copyright (c) 2003 by Joergen Ibsen / Jibz
## All Rights Reserved
##

target  = ../lib/libtinf.a
objects = tinflate.o tinfgzip.o tinfzlib.o adler32.o crc32.o

cflags  = -s -Wall -Os -fomit-frame-pointer

.PHONY: all clean

all: $(target)

$(target): $(objects)
	$(RM) $@
	ar -frsv $@ $^
	ranlib $@

%.o : %.c %.S
	avr-gcc $(cflags) -o $@ -c $<

clean:
	$(RM) $(target) $(objects)
